services:
  db:
    image: postgres:16
    container_name: projeto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sistema_doacoes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: