-- Active: 1759353781911@@bdong-nhui.j.aivencloud.com@15697@ong
-- Drop tabelas de associação primeiro
DROP TABLE IF EXISTS CampanhaFormaPagamento CASCADE;
DROP TABLE IF EXISTS CampanhaTipoDoacao CASCADE;

-- Drop tabelas principais
DROP TABLE IF EXISTS Recibo CASCADE;
DROP TABLE IF EXISTS Doacao CASCADE;
DROP TABLE IF EXISTS TipoDoacao CASCADE;
DROP TABLE IF EXISTS FormaPagamento CASCADE;
DROP TABLE IF EXISTS Status CASCADE;
DROP TABLE IF EXISTS Campanha CASCADE;
DROP TABLE IF EXISTS Endereco CASCADE;
DROP TABLE IF EXISTS Pessoa CASCADE;
